import 'package:flutter/widgets.dart';

/// Small app-owned localization layer for the four languages supported by the
/// profile and offline voice input. Unmapped dynamic content (names, SOS text,
/// room names, and server messages) is deliberately left untouched.
class MeshLocalizations {
  const MeshLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [
    Locale('en'),
    Locale('hi'),
    Locale('mr'),
    Locale('gu'),
    Locale('as'),
    Locale('bn'),
    Locale('kn'),
    Locale('ml'),
    Locale('pa'),
    Locale('ta'),
    Locale('te'),
  ];

  static const delegate = _MeshLocalizationsDelegate();

  static MeshLocalizations of(BuildContext context) =>
      Localizations.of<MeshLocalizations>(context, MeshLocalizations) ??
      const MeshLocalizations(Locale('en'));

  String text(String value) =>
      _translations[locale.languageCode]?[value] ?? value;

  String languageName(String code) => switch (code) {
    'hi' => text('Hindi'),
    'mr' => text('Marathi'),
    'gu' => text('Gujarati'),
    'as' => 'অসমীয়া',
    'bn' => 'বাংলা',
    'kn' => 'ಕನ್ನಡ',
    'ml' => 'മലയാളം',
    'pa' => 'ਪੰਜਾਬੀ',
    'ta' => 'தமிழ்',
    'te' => 'తెలుగు',
    _ => text('English'),
  };

  String holdToActivate(int seconds) => switch (locale.languageCode) {
    'hi' => 'आपातकालीन प्रोटोकॉल सक्रिय करने के लिए $seconds सेकंड दबाकर रखें',
    'mr' => 'आपत्कालीन प्रक्रिया सुरू करण्यासाठी $seconds सेकंद दाबून ठेवा',
    'gu' => 'કટોકટી પ્રોટોકોલ સક્રિય કરવા માટે $seconds સેકન્ડ દબાવી રાખો',
    _ => 'Press and hold for $seconds seconds to activate emergency protocol',
  };
}

extension MeshLocalizationsContext on BuildContext {
  MeshLocalizations get meshL10n => MeshLocalizations.of(this);
}

class _MeshLocalizationsDelegate
    extends LocalizationsDelegate<MeshLocalizations> {
  const _MeshLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => MeshLocalizations.supportedLocales.any(
    (supported) => supported.languageCode == locale.languageCode,
  );

  @override
  Future<MeshLocalizations> load(Locale locale) async =>
      MeshLocalizations(locale);

  @override
  bool shouldReload(_MeshLocalizationsDelegate old) => false;
}

const _translations = <String, Map<String, String>>{
  'hi': {
    'Home': 'होम',
    'Rooms': 'कमरे',
    'Activity': 'गतिविधि',
    'You': 'आप',
    'Profile': 'प्रोफ़ाइल',
    'Settings': 'सेटिंग्स',
    'Language': 'भाषा',
    'Preferred language': 'पसंदीदा भाषा',
    'English': 'अंग्रेज़ी',
    'Hindi': 'हिन्दी',
    'Marathi': 'मराठी',
    'Gujarati': 'गुजराती',
    'Emergency Aid': 'आपातकालीन सहायता',
    'One tap away from help': 'मदद बस एक टैप दूर',
    'Open profile': 'प्रोफ़ाइल खोलें',
    'Emergency type': 'आपातकाल का प्रकार',
    'Voice input': 'आवाज़ से जानकारी',
    'Speak details': 'विवरण बोलें',
    'Tap to record again': 'फिर से रिकॉर्ड करने के लिए टैप करें',
    'Describe SOS': 'SOS का विवरण दें',
    'Add context': 'जानकारी जोड़ें',
    'Create': 'बनाएँ',
    'Join': 'जुड़ें',
    'Coordinate securely with people nearby':
        'पास के लोगों के साथ सुरक्षित रूप से समन्वय करें',
    'Medical information': 'चिकित्सा जानकारी',
    'Trusted contacts': 'विश्वसनीय संपर्क',
    'Reporter ID': 'रिपोर्टर आईडी',
    'Blood type': 'रक्त समूह',
    'Allergies': 'एलर्जी',
    'Medical conditions': 'चिकित्सीय स्थितियाँ',
    'Not provided': 'नहीं दिया गया',
    'Edit emergency profile': 'आपातकालीन प्रोफ़ाइल संपादित करें',
    'Edit profile': 'प्रोफ़ाइल संपादित करें',
    'Accessibility': 'सुलभता',
    'High contrast mode': 'उच्च कॉन्ट्रास्ट मोड',
    'Dark mode': 'डार्क मोड',
    'Emergency settings': 'आपातकालीन सेटिंग्स',
    'Attach location to SOS': 'SOS के साथ स्थान जोड़ें',
    'Location details': 'स्थान विवरण',
    'Reprogram gestures': 'जेस्चर बदलें',
    'Emergency gateway': 'आपातकालीन गेटवे',
    'Save emergency profile': 'आपातकालीन प्रोफ़ाइल सहेजें',
    'Your details': 'आपकी जानकारी',
    'Emergency contacts': 'आपातकालीन संपर्क',
    'Medical details': 'चिकित्सा विवरण',
    'Try again': 'फिर से प्रयास करें',
    'Create profile': 'प्रोफ़ाइल बनाएँ',
    'Profile unavailable': 'प्रोफ़ाइल उपलब्ध नहीं है',
    'Connectivity': 'कनेक्टिविटी',
  },
  'mr': {
    'Home': 'मुख्यपृष्ठ',
    'Rooms': 'रूम्स',
    'Activity': 'क्रियाकलाप',
    'You': 'तुम्ही',
    'Profile': 'प्रोफाइल',
    'Settings': 'सेटिंग्ज',
    'Language': 'भाषा',
    'Preferred language': 'पसंतीची भाषा',
    'English': 'इंग्रजी',
    'Hindi': 'हिंदी',
    'Marathi': 'मराठी',
    'Gujarati': 'गुजराती',
    'Emergency Aid': 'आपत्कालीन मदत',
    'One tap away from help': 'मदत फक्त एका टॅपवर',
    'Open profile': 'प्रोफाइल उघडा',
    'Emergency type': 'आपत्कालाचा प्रकार',
    'Voice input': 'आवाजाने माहिती',
    'Speak details': 'तपशील सांगा',
    'Tap to record again': 'पुन्हा रेकॉर्ड करण्यासाठी टॅप करा',
    'Describe SOS': 'SOS चे वर्णन करा',
    'Add context': 'माहिती जोडा',
    'Create': 'तयार करा',
    'Join': 'सामील व्हा',
    'Coordinate securely with people nearby':
        'जवळच्या लोकांशी सुरक्षितपणे समन्वय साधा',
    'Medical information': 'वैद्यकीय माहिती',
    'Trusted contacts': 'विश्वासू संपर्क',
    'Reporter ID': 'रिपोर्टर आयडी',
    'Blood type': 'रक्तगट',
    'Allergies': 'अॅलर्जी',
    'Medical conditions': 'वैद्यकीय स्थिती',
    'Not provided': 'दिलेली नाही',
    'Edit emergency profile': 'आपत्कालीन प्रोफाइल संपादित करा',
    'Edit profile': 'प्रोफाइल संपादित करा',
    'Accessibility': 'सुलभता',
    'High contrast mode': 'उच्च कॉन्ट्रास्ट मोड',
    'Dark mode': 'डार्क मोड',
    'Emergency settings': 'आपत्कालीन सेटिंग्ज',
    'Attach location to SOS': 'SOS सह स्थान जोडा',
    'Location details': 'स्थान तपशील',
    'Reprogram gestures': 'जेस्चर बदला',
    'Emergency gateway': 'आपत्कालीन गेटवे',
    'Save emergency profile': 'आपत्कालीन प्रोफाइल जतन करा',
    'Your details': 'तुमची माहिती',
    'Emergency contacts': 'आपत्कालीन संपर्क',
    'Medical details': 'वैद्यकीय तपशील',
    'Try again': 'पुन्हा प्रयत्न करा',
    'Create profile': 'प्रोफाइल तयार करा',
    'Profile unavailable': 'प्रोफाइल उपलब्ध नाही',
    'Connectivity': 'कनेक्टिव्हिटी',
  },
  'gu': {
    'Home': 'હોમ',
    'Rooms': 'રૂમ્સ',
    'Activity': 'પ્રવૃત્તિ',
    'You': 'તમે',
    'Profile': 'પ્રોફાઇલ',
    'Settings': 'સેટિંગ્સ',
    'Language': 'ભાષા',
    'Preferred language': 'પસંદગીની ભાષા',
    'English': 'અંગ્રેજી',
    'Hindi': 'હિન્દી',
    'Marathi': 'મરાઠી',
    'Gujarati': 'ગુજરાતી',
    'Emergency Aid': 'કટોકટી સહાય',
    'One tap away from help': 'મદદ એક ટેપ દૂર છે',
    'Open profile': 'પ્રોફાઇલ ખોલો',
    'Emergency type': 'કટોકટીનો પ્રકાર',
    'Voice input': 'અવાજ ઇનપુટ',
    'Speak details': 'વિગતો બોલો',
    'Tap to record again': 'ફરી રેકોર્ડ કરવા ટેપ કરો',
    'Describe SOS': 'SOS નું વર્ણન કરો',
    'Add context': 'માહિતી ઉમેરો',
    'Create': 'બનાવો',
    'Join': 'જોડાઓ',
    'Coordinate securely with people nearby':
        'નજીકના લોકો સાથે સુરક્ષિત રીતે સંકલન કરો',
    'Medical information': 'તબીબી માહિતી',
    'Trusted contacts': 'વિશ્વસનીય સંપર્કો',
    'Reporter ID': 'રિપોર્ટર આઈડી',
    'Blood type': 'રક્ત પ્રકાર',
    'Allergies': 'એલર્જી',
    'Medical conditions': 'તબીબી સ્થિતિઓ',
    'Not provided': 'આપેલ નથી',
    'Edit emergency profile': 'કટોકટી પ્રોફાઇલ સંપાદિત કરો',
    'Edit profile': 'પ્રોફાઇલ સંપાદિત કરો',
    'Accessibility': 'સુગમતા',
    'High contrast mode': 'ઉચ્ચ કોન્ટ્રાસ્ટ મોડ',
    'Dark mode': 'ડાર્ક મોડ',
    'Emergency settings': 'કટોકટી સેટિંગ્સ',
    'Attach location to SOS': 'SOS સાથે સ્થાન જોડો',
    'Location details': 'સ્થાન વિગતો',
    'Reprogram gestures': 'જેશ્ચર બદલો',
    'Emergency gateway': 'કટોકટી ગેટવે',
    'Save emergency profile': 'કટોકટી પ્રોફાઇલ સાચવો',
    'Your details': 'તમારી વિગતો',
    'Emergency contacts': 'કટોકટી સંપર્કો',
    'Medical details': 'તબીબી વિગતો',
    'Try again': 'ફરી પ્રયાસ કરો',
    'Create profile': 'પ્રોફાઇલ બનાવો',
    'Profile unavailable': 'પ્રોફાઇલ ઉપલબ્ધ નથી',
    'Connectivity': 'કનેક્ટિવિટી',
  },
  'as': {
    'Home': 'হোম',
    'Rooms': 'কক্ষসমূহ',
    'Activity': 'কাৰ্যকলাপ',
    'You': 'আপুনি',
    'Profile': 'প্ৰ’ফাইল',
    'Settings': 'ছেটিংছ',
    'Language': 'ভাষা',
    'Preferred language': 'পছন্দৰ ভাষা',
    'Emergency Aid': 'জৰুৰী সহায়',
    'One tap away from help': 'সহায় মাত্ৰ এটা টেপ দূৰত',
    'Emergency type': 'জৰুৰী অৱস্থাৰ ধৰণ',
    'Voice input': 'কণ্ঠ ইনপুট',
    'Speak details': 'বিৱৰণ কওক',
    'Tap to record again': 'আকৌ ৰেকৰ্ড কৰিবলৈ টেপ কৰক',
    'Describe SOS': 'SOS বৰ্ণনা কৰক',
    'Add context': 'তথ্য যোগ কৰক',
    'Create': 'সৃষ্টি কৰক',
    'Join': 'যোগদান কৰক',
    'Medical information': 'চিকিৎসা তথ্য',
    'Trusted contacts': 'বিশ্বাসযোগ্য যোগাযোগ',
    'Reporter ID': 'ৰিপ’ৰ্টাৰ আইডি',
    'Blood type': 'ৰক্তৰ প্ৰকাৰ',
    'Allergies': 'এলাৰ্জি',
    'Medical conditions': 'চিকিৎসা অৱস্থা',
    'Not provided': 'দিয়া হোৱা নাই',
    'Edit emergency profile': 'জৰুৰী প্ৰ’ফাইল সম্পাদনা কৰক',
    'Accessibility': 'সুলভতা',
    'Emergency settings': 'জৰুৰী ছেটিংছ',
    'Connectivity': 'সংযোগ',
  },
  'bn': {
    'Home': 'হোম',
    'Rooms': 'রুম',
    'Activity': 'কার্যকলাপ',
    'You': 'আপনি',
    'Profile': 'প্রোফাইল',
    'Settings': 'সেটিংস',
    'Language': 'ভাষা',
    'Preferred language': 'পছন্দের ভাষা',
    'Emergency Aid': 'জরুরি সহায়তা',
    'One tap away from help': 'সাহায্য এক ট্যাপ দূরে',
    'Emergency type': 'জরুরি অবস্থার ধরন',
    'Voice input': 'ভয়েস ইনপুট',
    'Speak details': 'বিস্তারিত বলুন',
    'Tap to record again': 'আবার রেকর্ড করতে ট্যাপ করুন',
    'Describe SOS': 'SOS বর্ণনা করুন',
    'Add context': 'তথ্য যোগ করুন',
    'Create': 'তৈরি করুন',
    'Join': 'যোগ দিন',
    'Medical information': 'চিকিৎসা তথ্য',
    'Trusted contacts': 'বিশ্বস্ত পরিচিতি',
    'Reporter ID': 'রিপোর্টার আইডি',
    'Blood type': 'রক্তের ধরন',
    'Allergies': 'অ্যালার্জি',
    'Medical conditions': 'চিকিৎসাগত অবস্থা',
    'Not provided': 'দেওয়া হয়নি',
    'Edit emergency profile': 'জরুরি প্রোফাইল সম্পাদনা করুন',
    'Accessibility': 'সহজলভ্যতা',
    'Emergency settings': 'জরুরি সেটিংস',
    'Connectivity': 'সংযোগ',
  },
  'kn': {
    'Home': 'ಮುಖಪುಟ',
    'Rooms': 'ಕೊಠಡಿಗಳು',
    'Activity': 'ಚಟುವಟಿಕೆ',
    'You': 'ನೀವು',
    'Profile': 'ಪ್ರೊಫೈಲ್',
    'Settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'Language': 'ಭಾಷೆ',
    'Preferred language': 'ಆದ್ಯತೆಯ ಭಾಷೆ',
    'Emergency Aid': 'ತುರ್ತು ನೆರವು',
    'One tap away from help': 'ಸಹಾಯ ಒಂದು ಟ್ಯಾಪ್ ದೂರದಲ್ಲಿದೆ',
    'Emergency type': 'ತುರ್ತು ಸ್ಥಿತಿಯ ವಿಧ',
    'Voice input': 'ಧ್ವನಿ ಇನ್‌ಪುಟ್',
    'Speak details': 'ವಿವರಗಳನ್ನು ಹೇಳಿ',
    'Tap to record again': 'ಮತ್ತೆ ರೆಕಾರ್ಡ್ ಮಾಡಲು ಟ್ಯಾಪ್ ಮಾಡಿ',
    'Describe SOS': 'SOS ವಿವರಿಸಿ',
    'Add context': 'ಮಾಹಿತಿ ಸೇರಿಸಿ',
    'Create': 'ರಚಿಸಿ',
    'Join': 'ಸೇರಿ',
    'Medical information': 'ವೈದ್ಯಕೀಯ ಮಾಹಿತಿ',
    'Trusted contacts': 'ವಿಶ್ವಾಸಾರ್ಹ ಸಂಪರ್ಕಗಳು',
    'Reporter ID': 'ವರದಿಗಾರರ ಐಡಿ',
    'Blood type': 'ರಕ್ತದ ಗುಂಪು',
    'Allergies': 'ಅಲರ್ಜಿಗಳು',
    'Medical conditions': 'ವೈದ್ಯಕೀಯ ಸ್ಥಿತಿಗಳು',
    'Not provided': 'ನೀಡಲಾಗಿಲ್ಲ',
    'Edit emergency profile': 'ತುರ್ತು ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ',
    'Accessibility': 'ಪ್ರವೇಶಸಾಧ್ಯತೆ',
    'Emergency settings': 'ತುರ್ತು ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'Connectivity': 'ಸಂಪರ್ಕ',
  },
  'ml': {
    'Home': 'ഹോം',
    'Rooms': 'മുറികൾ',
    'Activity': 'പ്രവർത്തനം',
    'You': 'നിങ്ങൾ',
    'Profile': 'പ്രൊഫൈൽ',
    'Settings': 'ക്രമീകരണങ്ങൾ',
    'Language': 'ഭാഷ',
    'Preferred language': 'ഇഷ്ടഭാഷ',
    'Emergency Aid': 'അടിയന്തര സഹായം',
    'One tap away from help': 'സഹായം ഒരു ടാപ്പ് അകലെയാണ്',
    'Emergency type': 'അടിയന്തരാവസ്ഥയുടെ തരം',
    'Voice input': 'വോയ്സ് ഇൻപുട്ട്',
    'Speak details': 'വിശദാംശങ്ങൾ പറയുക',
    'Tap to record again': 'വീണ്ടും റെക്കോർഡ് ചെയ്യാൻ ടാപ്പ് ചെയ്യുക',
    'Describe SOS': 'SOS വിവരിക്കുക',
    'Add context': 'വിവരം ചേർക്കുക',
    'Create': 'സൃഷ്ടിക്കുക',
    'Join': 'ചേരുക',
    'Medical information': 'വൈദ്യ വിവരങ്ങൾ',
    'Trusted contacts': 'വിശ്വസ്ത ബന്ധങ്ങൾ',
    'Reporter ID': 'റിപ്പോർട്ടർ ഐഡി',
    'Blood type': 'രക്തഗ്രൂപ്പ്',
    'Allergies': 'അലർജികൾ',
    'Medical conditions': 'വൈദ്യ അവസ്ഥകൾ',
    'Not provided': 'നൽകിയിട്ടില്ല',
    'Edit emergency profile': 'അടിയന്തര പ്രൊഫൈൽ തിരുത്തുക',
    'Accessibility': 'പ്രവേശനസൗകര്യം',
    'Emergency settings': 'അടിയന്തര ക്രമീകരണങ്ങൾ',
    'Connectivity': 'കണക്റ്റിവിറ്റി',
  },
  'pa': {
    'Home': 'ਹੋਮ',
    'Rooms': 'ਕਮਰੇ',
    'Activity': 'ਸਰਗਰਮੀ',
    'You': 'ਤੁਸੀਂ',
    'Profile': 'ਪ੍ਰੋਫਾਈਲ',
    'Settings': 'ਸੈਟਿੰਗਾਂ',
    'Language': 'ਭਾਸ਼ਾ',
    'Preferred language': 'ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ',
    'Emergency Aid': 'ਐਮਰਜੈਂਸੀ ਸਹਾਇਤਾ',
    'One tap away from help': 'ਮਦਦ ਇੱਕ ਟੈਪ ਦੂਰ ਹੈ',
    'Emergency type': 'ਐਮਰਜੈਂਸੀ ਦੀ ਕਿਸਮ',
    'Voice input': 'ਆਵਾਜ਼ ਇਨਪੁਟ',
    'Speak details': 'ਵੇਰਵੇ ਬੋਲੋ',
    'Tap to record again': 'ਦੁਬਾਰਾ ਰਿਕਾਰਡ ਕਰਨ ਲਈ ਟੈਪ ਕਰੋ',
    'Describe SOS': 'SOS ਦਾ ਵਰਣਨ ਕਰੋ',
    'Add context': 'ਜਾਣਕਾਰੀ ਸ਼ਾਮਲ ਕਰੋ',
    'Create': 'ਬਣਾਓ',
    'Join': 'ਸ਼ਾਮਲ ਹੋਵੋ',
    'Medical information': 'ਮੈਡੀਕਲ ਜਾਣਕਾਰੀ',
    'Trusted contacts': 'ਭਰੋਸੇਯੋਗ ਸੰਪਰਕ',
    'Reporter ID': 'ਰਿਪੋਰਟਰ ਆਈਡੀ',
    'Blood type': 'ਖੂਨ ਦੀ ਕਿਸਮ',
    'Allergies': 'ਐਲਰਜੀ',
    'Medical conditions': 'ਮੈਡੀਕਲ ਸਥਿਤੀਆਂ',
    'Not provided': 'ਨਹੀਂ ਦਿੱਤਾ ਗਿਆ',
    'Edit emergency profile': 'ਐਮਰਜੈਂਸੀ ਪ੍ਰੋਫਾਈਲ ਸੋਧੋ',
    'Accessibility': 'ਪਹੁੰਚਯੋਗਤਾ',
    'Emergency settings': 'ਐਮਰਜੈਂਸੀ ਸੈਟਿੰਗਾਂ',
    'Connectivity': 'ਕਨੈਕਟੀਵਿਟੀ',
  },
  'ta': {
    'Home': 'முகப்பு',
    'Rooms': 'அறைகள்',
    'Activity': 'செயல்பாடு',
    'You': 'நீங்கள்',
    'Profile': 'சுயவிவரம்',
    'Settings': 'அமைப்புகள்',
    'Language': 'மொழி',
    'Preferred language': 'விருப்பமான மொழி',
    'Emergency Aid': 'அவசர உதவி',
    'One tap away from help': 'உதவி ஒரு தட்டல் தொலைவில் உள்ளது',
    'Emergency type': 'அவசரநிலை வகை',
    'Voice input': 'குரல் உள்ளீடு',
    'Speak details': 'விவரங்களைப் பேசுங்கள்',
    'Tap to record again': 'மீண்டும் பதிவு செய்ய தட்டவும்',
    'Describe SOS': 'SOS விவரிக்கவும்',
    'Add context': 'தகவலைச் சேர்க்கவும்',
    'Create': 'உருவாக்கு',
    'Join': 'சேர்',
    'Medical information': 'மருத்துவ தகவல்',
    'Trusted contacts': 'நம்பகமான தொடர்புகள்',
    'Reporter ID': 'தகவலளிப்பவர் ஐடி',
    'Blood type': 'இரத்த வகை',
    'Allergies': 'ஒவ்வாமைகள்',
    'Medical conditions': 'மருத்துவ நிலைகள்',
    'Not provided': 'வழங்கப்படவில்லை',
    'Edit emergency profile': 'அவசர சுயவிவரத்தைத் திருத்து',
    'Accessibility': 'அணுகல்தன்மை',
    'Emergency settings': 'அவசர அமைப்புகள்',
    'Connectivity': 'இணைப்பு',
  },
  'te': {
    'Home': 'హోమ్',
    'Rooms': 'గదులు',
    'Activity': 'కార్యకలాపం',
    'You': 'మీరు',
    'Profile': 'ప్రొఫైల్',
    'Settings': 'సెట్టింగ్‌లు',
    'Language': 'భాష',
    'Preferred language': 'ఇష్టమైన భాష',
    'Emergency Aid': 'అత్యవసర సహాయం',
    'One tap away from help': 'సహాయం ఒక ట్యాప్ దూరంలో ఉంది',
    'Emergency type': 'అత్యవసర రకం',
    'Voice input': 'వాయిస్ ఇన్‌పుట్',
    'Speak details': 'వివరాలు చెప్పండి',
    'Tap to record again': 'మళ్లీ రికార్డ్ చేయడానికి ట్యాప్ చేయండి',
    'Describe SOS': 'SOS వివరించండి',
    'Add context': 'సమాచారం జోడించండి',
    'Create': 'సృష్టించండి',
    'Join': 'చేరండి',
    'Medical information': 'వైద్య సమాచారం',
    'Trusted contacts': 'విశ్వసనీయ పరిచయాలు',
    'Reporter ID': 'రిపోర్టర్ ఐడి',
    'Blood type': 'రక్త రకం',
    'Allergies': 'అలెర్జీలు',
    'Medical conditions': 'వైద్య పరిస్థితులు',
    'Not provided': 'అందించలేదు',
    'Edit emergency profile': 'అత్యవసర ప్రొఫైల్ సవరించండి',
    'Accessibility': 'ప్రాప్యత',
    'Emergency settings': 'అత్యవసర సెట్టింగ్‌లు',
    'Connectivity': 'కనెక్టివిటీ',
  },
};
